### ISSUE TITLE
Getting in touch

### ISSUE THREAD

**Issue by adamgajzlerowicz** [saschwarz/steve-agilitynerd#1]
Hello
I am making a React Native app for scheduling agility trainings. I am also an agility nerd like yourself, but ofc there is only one REAL Agility nerd and that is you :D

So far I have been working on the project by myself but I was wondering if you perhaps would like to collaborate on it?

Currently the app is only in polish, but I am hoping to expand out so am adding the English version of it.

It is my pet project. Checkout the website. https://agilix.dog
If you'd like to talk about it - lets!
Check me out on Linked in or facebook and lets chat

All the best from poland :D

**Comment by saschwarz** [comment]
@adamgajzlerowicz thanks for contacting me. Unfortunately, I'm too busy working on my own side project: https://agilitycoursemaster.com using Ionic. Version 2.0 releasing soon!

Best regards.

**Comment by adamgajzlerowicz** [comment]
It looks really cool! What happened to the Android version? :D

**Comment by saschwarz** [comment]
Google requires that I upgrade it. I'm no longer making native builds. The next versions are PWAs that run on all mobile and desktop versions

**Comment by adamgajzlerowicz** [comment]
Building a native app is so much harder than making a website. Both platforms need to be considered separate, and each version of the api has to be fully backwards compatible. No removals or updates. Just additions. And if you release a bugged app version... it may take weeks before users do the upgrade.

But native app has notifications and better performance. I guess you loose some and you get some.

Nevertheless - if you need any help with your app let me know.
I am having some struggles on my own. Currently trying to figure out if I should monetize. And if the answer is yes, then how to model the app. It's not a priority for me to do this really as I enjoy working on it on its own, but It's an interesting challenge to face. 

Stay in touch and good luck with your app.
